<a href="https://colab.research.google.com/github/Uwais-ur-Rehman/ML-Project/blob/main/Averaging_Esembling_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/placement.csv')

In [3]:
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [4]:
df.isnull().sum()

cgpa       0
package    0
dtype: int64

In [5]:
x=df.iloc[:,:-1]
y=df['package']

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [8]:
lr=LinearRegression()
dtr=DecisionTreeRegressor()
svr=SVR()

In [9]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)*100,lr.score(x_test,y_test)*100

(78.13227298629096, 72.97167943957027)

In [10]:
dtr.fit(x_train,y_train)
dtr.score(x_train,y_train)*100,dtr.score(x_test,y_test)*100

(96.52365092501411, 33.330923112011654)

In [11]:
svr.fit(x_train,y_train)
svr.score(x_train,y_train)*100,svr.score(x_test,y_test)*100

(79.27772674182569, 70.9603389259618)

In [12]:
from sklearn.ensemble import VotingRegressor

In [13]:
voting_regressor=VotingRegressor([('lr',lr),('dtr',dtr),('svr',svr)])
voting_regressor.fit(x_train,y_train)
voting_regressor.score(x_train,y_train)*100,voting_regressor.score(x_test,y_test)*100

(88.71879368267089, 65.12004922641455)

In [14]:
df=pd.DataFrame({"Linear Regression":lr.predict(x_test),"Decision Tree Regression":dtr.predict(x_test),"Support Vector Regression":svr.predict(x_test),"Voting Regressor":voting_regressor.predict(x_test)})

In [15]:
df

,Linear Regression,Decision Tree Regression,Support Vector Regression,Voting Regressor
0,2.970126,2.7600,2.967931,2.899353
1,2.555168,2.2350,2.581230,2.457133
2,2.618565,2.0900,2.636028,2.448198
3,3.402374,2.7600,3.421421,3.194598
4,3.056576,2.6350,3.050539,2.914038
5,2.359216,2.5700,2.403762,2.444326
6,3.517640,3.6700,3.569618,3.585753
7,2.468719,2.2600,2.506754,2.411824
8,4.122787,3.9100,4.106859,4.046549
9,3.217948,3.0900,3.209976,3.172641
10,2.128684,2.5500,2.106833,2.261839
11,3.194895,2.9900,3.186157,3.123684
12,2.537878,2.5850,2.566441,2.563106
13,3.050812,3.0000,3.045032,3.031948
14,3.367794,3.9600,3.378862,3.568885
15,2.860623,2.5600,2.862191,2.760938
16,2.630091,2.0900,2.646163,2.455418
17,2.820280,2.8200,2.823120,2.821133
18,2.370742,2.6000,2.415445,2.462062
19,2.918256,2.9300,2.918009,2.922088
20,3.166078,3.4300,3.157021,3.251033
21,2.336163,2.5875,2.379618,2.434427
22,3.506113,3.1400,3.554568,3.400227
23,3.990231,3.5200,4.048440,3.852890
24,2.203607,2.1000,2.216993,2.173533
25,1.909678,1.6300,1.763109,1.767596
26,3.085392,3.1300,3.078150,3.097847
27,2.607038,3.2300,2.625957,2.820998
28,1.921205,1.9800,1.779650,1.893618
29,1.903915,1.6300,1.754992,1.762969
30,2.912493,2.9300,2.912440,2.918311
31,3.696302,4.0800,3.793774,3.856692
32,2.601275,3.2300,2.620943,2.817406
33,2.094104,2.1600,2.052612,2.102239
34,2.509062,2.7600,2.541759,2.603607
35,3.644433,3.8900,3.731905,3.755446
36,3.171842,3.4300,3.162797,3.254880
37,2.970126,2.7600,2.967931,2.899353
38,3.834622,4.0300,3.935748,3.933457
39,2.503298,2.7600,2.536802,2.600033