<a href="https://colab.research.google.com/github/Uwais-ur-Rehman/ML-Project/blob/main/Ensemble_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv('/content/Exam_Score_Prediction.csv')
data.head(5)

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

In [ ]:
data['gender'].value_counts()

gender
other     6726
male      6695
female    6579
Name: count, dtype: int64

In [ ]:
data.isnull().sum()

student_id          0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder

# List of categorical columns to encode (excluding 'sleep_hours' as it is numerical)
categorical_cols = ['gender','course','internet_access','sleep_quality','study_method','facility_rating','exam_difficulty']

# Apply LabelEncoder to each categorical column
for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
data.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,1,6,2.78,92.9,1,7.4,2,0,1,1,58.9
1,2,23,2,5,3.37,64.8,1,4.6,0,3,2,2,54.8
2,3,22,1,1,7.88,76.8,1,8.5,2,0,0,2,90.3
3,4,20,2,6,0.67,48.4,1,5.8,0,3,1,2,29.7
4,5,20,0,6,0.89,71.6,1,9.8,2,0,1,2,43.7

In [ ]:
X= data.drop(['student_id','exam_score'],axis=1)
y=data['exam_score']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor()
rf.fit(X_train_scaled,y_train)

RandomForestRegressor()

In [ ]:
y_pred=rf.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
print(f'R2= ',r2_score(y_test,y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

R2=  0.6925771901355117
MSE: 109.96422229864426

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf1=RandomForestRegressor(n_estimators=100,random_state=42)
rf1.fit(X_train_scaled,y_train)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred1=rf.predict(X_test_scaled)

In [ ]:
print(f'R2= ',r2_score(y_test,y_pred1))
print("MSE:", mean_squared_error(y_test, y_pred1))

R2=  0.6925771901355117
MSE: 109.96422229864426