<a href="https://colab.research.google.com/github/Uwais-ur-Rehman/ML-Project/blob/main/Pandas0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
data= pd.read_csv("/content/customer_purchase_data.csv")

In [ ]:
data.head(3)

,CustomerID,CustomerName,Gender,Age,Country,Email,PurchaseAmount,PurchaseDate,ProductCategory,PaymentMethod,ReviewScore,IsMember
0,1,Evan Brown,Male,63.0,USA,user1@example.com,114.24,2025-02-10,Home,PayPal,NaN,True
1,2,Charlie Miller,Male,47.0,France,user2@example.com,473.64,2024-12-13,Toys,Credit Card,1.0,True
2,3,Alice Davis,Male,55.0,France,user3@example.com,392.84,2024-09-21,Groceries,Bank Transfer,1.0,True

In [ ]:
data.groupby(["Gender","Country"]).count()

                  CustomerID  CustomerName  Age  Email  PurchaseAmount  \
Gender Country
Female Australia           6             5    5      5               5
       Canada             10             8    9     10              10
       France             21            18   19     19              19
       Germany            16            14   13     16              15
       UK                 11            10    9     11               8
       USA                18            17   17     18              18
Male   Australia          10             9   10      9              10
       Canada             14            12   13     14              13
       France             11            10   10     11              10
       Germany            12            11   10     12              12
       UK                 11            11   10     11              10
       USA                10             9    9      9               9

                  PurchaseDate  ProductCategory  PaymentMethod  ReviewScore  \
Gender Country
Female Australia             6                6              6            6
       Canada               10               10             10           10
       France               21               21             21           20
       Germany              16               16             16           15
       UK                   11               11             11           10
       USA                  18               18             18           17
Male   Australia            10               10             10           10
       Canada               14               14             14           13
       France               11               11             11           10
       Germany              12               12             12           10
       UK                   11               11             11            9
       USA                  10               10             10            9

                  IsMember
Gender Country
Female Australia         6
       Canada           10
       France           21
       Germany          16
       UK               11
       USA              18
Male   Australia        10
       Canada           14
       France           11
       Germany          12
       UK               11
       USA              10

In [ ]:
data.isnull().sum()

CustomerID          0
CustomerName        0
Gender              0
Age                16
Country             0
Email               5
PurchaseAmount     11
PurchaseDate        0
ProductCategory     0
PaymentMethod       0
ReviewScore        11
IsMember            0
dtype: int64

In [ ]:
data.dtypes

CustomerID          object
CustomerName        object
Gender              object
Age                float64
Country             object
Email               object
PurchaseAmount     float64
PurchaseDate        object
ProductCategory     object
PaymentMethod       object
ReviewScore        float64
IsMember              bool
dtype: object

In [ ]:
data["CustomerName"].dtype
data["CustomerName"]=data["CustomerName"].fillna(data["CustomerName"].mode()[0])
data["Email"]=data["Email"].fillna(data["Email"].mode()[0])
data["ReviewScore"]=data["ReviewScore"].fillna(data["ReviewScore"].mode()[0])
mean_age=data["Age"].mean()
mean_purchase_amount=data["PurchaseAmount"].mean()
data["Age"]=data["Age"].fillna(mean_age)
data["PurchaseAmount"]=data["PurchaseAmount"].fillna(mean_purchase_amount)

In [ ]:
data.describe()

              Age  PurchaseAmount  ReviewScore
count  150.000000      150.000000   150.000000
mean    47.044776      264.914101     2.913333
std     13.944216      137.023773     1.409158
min     18.000000       16.700000     1.000000
25%     39.000000      143.232500     2.000000
50%     47.044776      264.914101     3.000000
75%     57.750000      380.062500     4.000000
max     70.000000      498.010000     5.000000

In [ ]:
data.isnull().sum()

CustomerID         0
CustomerName       0
Gender             0
Age                0
Country            0
Email              0
PurchaseAmount     0
PurchaseDate       0
ProductCategory    0
PaymentMethod      0
ReviewScore        0
IsMember           0
dtype: int64

In [ ]:
data["PurchaseAmount"].value_counts()

PurchaseAmount
264.914101    11
114.240000     1
392.840000     1
473.640000     1
65.600000      1
              ..
490.430000     1
307.960000     1
321.960000     1
281.860000     1
54.590000      1
Name: count, Length: 140, dtype: int64

In [ ]:
data.groupby("PaymentMethod").agg({"PurchaseAmount":["mean","sum","max","min"],
                                  "ProductCategory":"count"  })

              PurchaseAmount                              ProductCategory
                        mean           sum     max    min           count
PaymentMethod
Bank Transfer     283.724934  11632.722302  490.43  50.55              41
Credit Card       250.570603   9271.112302  484.64  16.70              37
Debit Card        274.775780   9617.152302  497.96  46.96              35
PayPal            249.084546   9216.128201  498.01  25.83              37

In [ ]:
bins=[0,18,25,35,55,70]
labels=["Teens","Young","Adults","Mid","Aged"]
data["AgeGroup"]=pd.cut(data["Age"],bins=bins,labels=labels)
data

,CustomerID,CustomerName,Gender,Age,Country,Email,PurchaseAmount,PurchaseDate,ProductCategory,PaymentMethod,ReviewScore,IsMember,AgeGroup
0,Evan Brown,Evan Brown,Male,63.000000,USA,user1@example.com,114.24,2025-02-10,Home,PayPal,2.0,True,Aged
1,Charlie Miller,Charlie Miller,Male,47.000000,France,user2@example.com,473.64,2024-12-13,Toys,Credit Card,1.0,True,Mid
2,Alice Davis,Alice Davis,Male,55.000000,France,user3@example.com,392.84,2024-09-21,Groceries,Bank Transfer,1.0,True,Mid
3,Charlie Jones,Charlie Jones,Female,55.000000,USA,user4@example.com,65.60,2025-03-09,Toys,PayPal,4.0,False,Mid
4,Evan Johnson,Evan Johnson,Female,62.000000,France,user5@example.com,466.16,2024-05-08,Toys,Credit Card,1.0,True,Aged
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,John Williams,John Williams,Male,18.000000,UK,user146@example.com,490.43,2025-01-22,Electronics,Bank Transfer,3.0,True,Teens
146,John Johnson,John Johnson,Male,64.000000,Germany,user147@example.com,307.96,2024-09-05,Toys,PayPal,5.0,True,Aged
147,Jane Brown,Jane Brown,Female,51.000000,USA,user148@example.com,321.96,2025-01-10,Home,PayPal,4.0,False,Mid
148,Diana Miller,Diana Miller,Male,47.044776,Germany,user149@example.com,281.86,2024-10-23,Toys,Debit Card,3.0,False,Mid
149,Charlie Davis,Charlie Davis,Female,65.000000,UK,user150@example.com,54.59,2024-06-17,Clothing,PayPal,2.0,True,Aged

In [ ]:
data["AgeGroupQcut"]=pd.qcut(data["Age"],5,labels=labels)
data

,CustomerID,CustomerName,Gender,Age,Country,Email,PurchaseAmount,PurchaseDate,ProductCategory,PaymentMethod,ReviewScore,IsMember,AgeGroup,AgeGroupQcut
0,Evan Brown,Evan Brown,Male,63.000000,USA,user1@example.com,114.24,2025-02-10,Home,PayPal,2.0,True,Aged,Aged
1,Charlie Miller,Charlie Miller,Male,47.000000,France,user2@example.com,473.64,2024-12-13,Toys,Credit Card,1.0,True,Mid,Adults
2,Alice Davis,Alice Davis,Male,55.000000,France,user3@example.com,392.84,2024-09-21,Groceries,Bank Transfer,1.0,True,Mid,Mid
3,Charlie Jones,Charlie Jones,Female,55.000000,USA,user4@example.com,65.60,2025-03-09,Toys,PayPal,4.0,False,Mid,Mid
4,Evan Johnson,Evan Johnson,Female,62.000000,France,user5@example.com,466.16,2024-05-08,Toys,Credit Card,1.0,True,Aged,Aged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,John Williams,John Williams,Male,18.000000,UK,user146@example.com,490.43,2025-01-22,Electronics,Bank Transfer,3.0,True,Teens,Teens
146,John Johnson,John Johnson,Male,64.000000,Germany,user147@example.com,307.96,2024-09-05,Toys,PayPal,5.0,True,Aged,Aged
147,Jane Brown,Jane Brown,Female,51.000000,USA,user148@example.com,321.96,2025-01-10,Home,PayPal,4.0,False,Mid,Mid
148,Diana Miller,Diana Miller,Male,47.044776,Germany,user149@example.com,281.86,2024-10-23,Toys,Debit Card,3.0,False,Mid,Adults
149,Charlie Davis,Charlie Davis,Female,65.000000,UK,user150@example.com,54.59,2024-06-17,Clothing,PayPal,2.0,True,Aged,Aged

In [ ]:
scores = np.random.randint(0, 101, 20)
df = pd.DataFrame({"Score": scores})
bins = [0, 59, 75, 89, 100]
labels = ["F", "C", "B", "A"]
df["Grade"] = pd.cut(df["Score"], bins=bins, labels=labels)
print("Scores with Grades:")
print(df)
print("\nGrade Counts:")
print(df["Grade"].value_counts())

Scores with Grades:
    Score Grade
0      79     B
1      38     F
2      42     F
3      55     F
4      97     A
5      96     A
6      38     F
7       0     F
8      26     F
9      50     F
10     80     B
11     89     B
12     72     C
13     69     C
14     11     F
15     90     A
16     85     B
17     53     F
18     88     B
19     41     F

Grade Counts:
Grade
F    10
B     5
A     3
C     2
Name: count, dtype: int64