<a href="https://colab.research.google.com/github/Uwais-ur-Rehman/ML-Project/blob/main/Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [133]:
df=pd.read_csv('/content/House Price Prediction Dataset.csv')

In [134]:
df.head(2)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998

In [135]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [136]:
df['Condition'].nunique()

4

In [137]:
df['Location'].nunique()

4

In [138]:
x=df.drop(['Price','Id'],axis=1)
y=df['Price']

In [139]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [140]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [141]:
numerical_cols=['Area','Bedrooms','Bathrooms','Floors','YearBuilt']
categorical_cols=['Location','Condition','Garage']

In [142]:
preprocessor=ColumnTransformer(
    transformers=[
        ('num',MinMaxScaler(),numerical_cols),
        ('cat',OneHotEncoder(sparse_output=False,drop='first',handle_unknown="ignore"),categorical_cols)
    ]
)

In [143]:
model=Pipeline([
    ("preprcessor",preprocessor),
    ("regressor",LinearRegression())
])

In [144]:
model.fit(x_train,y_train)

Pipeline(steps=[('preprcessor',
                 ColumnTransformer(transformers=[('num', MinMaxScaler(),
                                                  ['Area', 'Bedrooms',
                                                   'Bathrooms', 'Floors',
                                                   'YearBuilt']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Location', 'Condition',
                                                   'Garage'])])),
                ('regressor', LinearRegression())])

In [145]:
y_pred = model.predict(x_test)

In [146]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)*100
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 243241.97758826384
MSE: 78321466146.0328
RMSE: 279859.72583784326
R²: -0.6717808430749761